DECLARE @REQUIRED_METHODOLOGY_ITER  NVARCHAR(MAX);
DECLARE @PERCENT_TOTAL DECIMAL(3, 2);

DECLARE RM_CURSOR CURSOR FAST_FORWARD
	FOR
		SELECT C2.REQUIRED_METHODOLOGY
			,ROUND(C2.ROW_COUNT / CAST(C2.TOTAL_COUNT AS FLOAT), 2) AS PERCENT_TOTAL
		FROM (
		SELECT C1.REQUIRED_METHODOLOGY
			,C1.ROW_COUNT
			,SUM(C1.ROW_COUNT) OVER() AS TOTAL_COUNT
		FROM (
		SELECT C.REQUIRED_METHODOLOGY
			,COUNT(*) AS ROW_COUNT
		FROM (
		SELECT M.REQUIRED_METHODOLOGY
		FROM DW_PROPERTY_VALUATION.dbo.FACT_PROPERTY_VALUATION_NEW F WITH(NOLOCK)
		LEFT JOIN DW_PROPERTY_VALUATION.dbo.vw_FACT_REQUIRED_METHODOLOGY M WITH(NOLOCK) ON F.PROPERTY_KEY = M.PROPERTY_KEY
			AND F.VALUATION_DATE_KEY = M.VALUATION_DATE
		WHERE M.REQUIRED_METHODOLOGY IS NOT NULL
		) C
		GROUP BY  C.REQUIRED_METHODOLOGY
		) C1
		) C2
		WHERE ROUND(C2.ROW_COUNT / CAST(C2.TOTAL_COUNT AS FLOAT), 2) > .05;

OPEN RM_CURSOR
FETCH NEXT FROM RM_CURSOR
	INTO @REQUIRED_METHODOLOGY_ITER
		,@PERCENT_TOTAL
	WHILE @@FETCH_STATUS = 0
	BEGIN
		PRINT @REQUIRED_METHODOLOGY_ITER
		PRINT @PERCENT_TOTAL
		FETCH NEXT FROM RM_CURSOR
			INTO @REQUIRED_METHODOLOGY_ITER
				,@PERCENT_TOTAL
	END
CLOSE RM_CURSOR
DEALLOCATE RM_CURSOR