DECLARE @PM11_BOM_Date DATETIME = '20201201';
DECLARE @PM11_BOM_String VARCHAR(8);
SET @PM11_BOM_String = FORMAT(@PM11_BOM_Date, 'MMM_yyyy');

DROP TABLE IF EXISTS #Test1;

CREATE TABLE #Test1 (
RP VARCHAR(8)
);

SELECT * FROM #Test1

EXEC TEMPDB.SYS.SP_RENAME '#Test1.RP', @PM11_BOM_String, 'COLUMN';

SELECT * FROM #Test1