USE DW_LOAN_VALUATION
GO

SELECT
	'DROP TABLE ' + S.NAME + '.' + T.NAME + ';' AS DROP_TABLE_SQL
FROM SYS.TABLES T
INNER JOIN SYS.SCHEMAS S
	ON T.SCHEMA_ID = S.SCHEMA_ID
WHERE
	S.NAME = 'archive'